name: Update RDS Security Group

on:
  push:
    branches:
      - railway-connect-api

jobs:
  update-security-group:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get public IP
        id: ip
        run: |
          echo "IP=$(curl -s https://api.ipify.org)" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Authorize IP in Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id sg-07e6b696f4d7029ac \
            --protocol tcp \
            --port 1433 \
            --cidr ${{ steps.ip.outputs.IP }}/32 || echo "IP already authorized or error occurred"
